model_runner: models.nemo_runner.run_nemo
model_name_or_path: /home/user/.cache/nemo_experiments/Speech_To_Text_Finetuning/2025-07-22_06-58-20/checkpoints/Speech_To_Text_Finetuning.nemo
dataset: hsekhalilian/fleurs
split: validation
